name: POCONE/POCONE
on:
  push:
    branches:
    - "*"
env:
  name: medica
jobs:
  scripts:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - run: echo "This step runs in the default shell"
    - run: echo "This step runs in bash"
      shell: bash
    - run: Write-Host "This step runs in PowerShell Core"
      shell: pwsh
    - run: Write-Host "This step runs in PowerShell"
      shell: powershell
  run_command:
    runs-on: windows-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - run: echo "This step runs in CMD on Windows by default"
  conditional:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - if: env.str == 'ABC' && env.num == 123
      run: echo "This step runs with str equals 'ABC' and num equals 123"
  initial:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - run: echo "This job will be run first."
  fanout1:
    needs:
    - initial
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - run: echo "This job will run after the initial job, in parallel with fanout2."
  fanout2:
    needs:
    - initial
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - run: echo "This job will run after the initial job, in parallel with fanout1."
  fanin:
    needs:
    - fanout1
    - fanout2
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - run: echo "This job will run after fanout1 and fanout2 have finished."
  run_python:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - uses: actions/setup-python@v5.0.0
      with:
        python-version: 3.10.19
        architecture: x64
    - run: python script.py
  environmental_variables:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - run: echo "printing env variable name = ${{ env.NAME }}"
    - run: echo "printing secrets variable secret_name = ${{ secrets.SECRET_NAME }}"
    - if: env.secret_name == 'medica_secret'
      run: echo "matched"
